### PR TITLE
Add examples to README

### PR DESCRIPTION
**Pull request by xnl-h4ck3r**
Hi
Someone suggested the format would be better like https://github.com/dwisiswant0/awesome-oneliner-bugbounty#readme for example, which I liked. 
I have added your examples to README, plus the examples provided by PortSwigger, and a great one from @yougina.
Im'm not sure if you like this format or not. If not, I can recreate them in separate folders instead like your original examples.
Thanks
Xnl

### CODE REVIEW

**Comment by xnl-h4ck3r** [comment]
I also added a new bambda query that I created

**Review by prodigysml — APPROVED** [review]

**Comment by prodigysml** [comment]
Thanks for the awesome PR @xnl-h4ck3r ! Def great improvements!

**Comment by xnl-h4ck3r** [comment]
Thanks for adding it in! Hopefully a lot more people will add theirs too :)
Just wondering, should I be able to see myself as a Contributer on the repo page?

**Comment by prodigysml** [comment]
Any time! Good question actually! I'm not too sure where it will be shown publicly, but I can see you as a contributor in `GitHub Insights`:
image

**Pull request merged**
